### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by Vimanse** [rs2k/raceflight#102]
make: *** No rule to make target 'CC3D'.  Stop.
when trying to compile,only compiles when ''make all''.CF compiles fine .Any body have this issue?.
code has changed so I am totally lost.Wheres the build config files?

**Comment by blckmn** [comment]
just did a build then - and it worked well for me. Here is the hex.
[raceflight_CC3D.zip](https://github.com/rs2k/raceflight/files/154474/raceflight_CC3D.zip)

**Comment by Vimanse** [comment]
SOLVED!! @blckmn  thanks
