### ISSUE TITLE
SPRACING F3+OSD

### ISSUE THREAD

**Issue by gamani** [rs2k/raceflight#104]
HI Guys,

I've tried to update the firmware of this board SP-Racing-F3-Flight-Controller-With-Integrated-OSD-for-FPV-Multicopter (please google it you'll find the infos)

But it doesn't work.

I think it's pretty easy to support raceflight for it.

Are you able to do this ?

Regards,
Alex

**Comment by gamani** [comment]
No answer till now ? great ...

**Comment by blckmn** [comment]
Sorry mate. We've just been flat out getting the latest changes from BF working on the F4s.

If this board is a direct clone of SPRF3 then that target should work. If it's not then it might need its own.

It'd be great if you could link all the details here.

**Comment by gamani** [comment]
Thanks for answering. In fact its a type of spracing F3 board that we've
developped, if you can give me your e-mail i would be happy forward you all
the details for sure.

**Comment by blckmn** [comment]
How many boards are being made? Be good if you could send a sample of one to one of the programmers here to test.

**Comment by gamani** [comment]
We're making 100 boards as first batch. But i can send you one of course.

Just give me your address and i will ship it.

**Comment by gamani** [comment]
Anyway here are some details 

MPU 6500
BARO BMP 280

The rest is the same as the SPRACING

**Comment by MJ666** [comment]
With the last changes on the MPU drivers you can include MPU6050 and MPU6050 driver into the same target.

**Comment by gamani** [comment]
Hi @MJ666 ! Yes i've updated the target.h and the makefile but i'm not sure about my changes. Maybe you can have a check ?

TARGET FROM SPRACINGF3
[target.txt](https://github.com/rs2k/raceflight/files/190833/target.txt)

Makefile at SPRACINGF3
[Makefile.txt](https://github.com/rs2k/raceflight/files/190832/Makefile.txt)

**Comment by MJ666** [comment]
If you are using the MPU6500 in I2C mode this schould be fine as it is now. What results do you get with this? I'm actualy not at home an can not give this an try to compile. For the MPU9250 there is an additionlal driver update required. likely an  It also should be posible to keep the MPU6050 driver in the target otherwise it will not work anymore with the orginal SPR F3.

**Comment by gamani** [comment]
So for 6500 without compass i've managed to compile it, and will test it tomorrow. Then when i add the line "drivers/compass_ak8963.c \" i got the following : ./src/main/drivers/compass_ak8963.c:140: undefined reference to `verifympu6500WriteRegister'. This is strange because on the previous version i've managed to compile it without error.

**Comment by gamani** [comment]
Just tested the compiled fw for 6500, well it's initialising but the esc bip are not so sync. The motors don't compensate in airmode and sometimes the board is reinitializing too. Since 2.4.0 update of betaflight i don't manage to make it work anymore. I have a working version on 2.3.5 if you want.

**Comment by gamani** [comment]
I think i will leave it to you guys. Any way to send you an FC ? You can send me your full address to atilamusic@gmail.com Also if you have skype or whatsapp, would be great too :)

**Comment by blckmn** [comment]
Just sent you an email.

**Comment by gamani** [comment]
Ok got it, just replied you ;)

**Comment by MJ666** [comment]
Betaflight is bit different to Raceflight. The AK8963 driver needs some tweaking. Actualy it expects if SPI is enabled it is part of an SPI connected MPU9250. It looks to be you already get attention from @blckmn.

**Comment by blckmn** [comment]
@MJ666 we might need to add in some specifics for how the AK8963 is connected perhaps a check for a 9250 first...

In this case I'm assuming the AK is connected via I2C...

Or we go with a specific 9250 driver... Thoughts?

**Comment by MJ666** [comment]
I think we likely need an specific MPU9250 I2C driver. This driver need to enable the I2C bypass. Cleanfligth has an working implementation for this for the SP Racing F3 mini. The AK8963 driver also need some tweaking. The SPI section should only be compiled in if the SPI MPU9250 is also present.

**Comment by MJ666** [comment]
@gamani please can you give this branch an try: https://github.com/MJ666/raceflight/tree/Zigogne

**Comment by MJ666** [comment]
@gamani  @blckmn My approach here was not to add an additional target but update the SPRACING3 target to support this controller since this is quite similar. 

https://github.com/rs2k/raceflight/pull/130

**Comment by blckmn** [comment]
Hi @MJ666 I did see that ... though I added an extra target to give the target board identifiers (so the imagery can be right). There's also possibly a serial pass through required for the OSD. 

I think we will eventually move away from somewhat away from specific targets - and focus on the chips installed (and how they are connected). Everything else will be configuration downloaded to the board.

**Comment by blckmn** [comment]
We can consolidate. Did you get the dodo working?

**Comment by MJ666** [comment]
I bench tested this on one of my dodo boards and it looks quite well. I have not done a flight test.

**Comment by nathantsoi** [comment]
maybe this is a lame question, how is this board different from the others currently available? e.g. 
- http://nathan.vertile.com/blog/2016/02/03/rctimer-beerotorf3-flight-controller/
- http://shop.myairbot.com/index.php/flip32f3aio-lite.html
- http://www.banggood.com/SP-Racing-F3-Flight-Controller-With-Integrated-OSD-for-FPV-Multicopter-p-1032369.html

**Comment by henn1001** [comment]
I think the topic here is about the third FC you linked..

**Comment by W3DRK** [comment]
I was just pointed to this thread a few minutes ago...  I actually tried rolling my own build of Betaflight 2.6.0 for this FC last night but didn't have much luck.  I did basically the same as suggested here, I duplicated the SPRF3 to a new target and swapped the gyro/accel parameters out for the MCU6500.  It compiles fine and when flashed the FC seems to work for about 10 seconds, then freezes.  If I keep it moving, it will continue to work, but if I hold it still after a few seconds it stops responding to the VCP. I didn't get a chance to test the motor controls.

**Comment by blckmn** [comment]
This one doesn't use VCP.

The drivers in Raceflight have had some work on them too ... So there are some underlying code differences. We have been quite active in that space.

**Comment by proggod** [comment]
Please test betas and see if this issue is in any of them, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
