### ISSUE TITLE
how to use the bin file

### ISSUE THREAD

**Issue by xfce** [rs2k/raceflight#11]
use st-jlink download at 0x08000000?

**Comment by rs2k** [comment]
For the revo and sparky2 the correct address is 0x08020000.
For the revo nano it's 0x08010000

You can upload the bin using the OP or TL bootloader and their GCS as well.

**Comment by xfce** [comment]
ok, thanks. I have flash the nano use OP's GCS-15.05.2,
it seems OK, alarm and status LED can flash, and on the PC list two STM32 Virtual ComPort in FS Mode, can't find the driver. Where can I find the driver?
another thing I use  CLEANFLIGHT configurator 1.1.0, does it OK? thanks!

**Comment by blackmanj** [comment]
http://www.st.com/web/en/catalog/tools/PF257938

Once you run the first install - navigate to the install directory, and run the .exe for your system (64bit or 32bit). The first install is not the driver - just an extractor for the driver.

**Comment by xfce** [comment]
OK , Thanks very much, I have fixed it. now all seems OK
