### ISSUE TITLE
能否在下一版本中加入fs-i6接收机的ibus的支持

### ISSUE THREAD

**Issue by pdwdw** [rs2k/raceflight#123]
能否在下一版本中加入fs-i6接收机的ibus的支持

Can the RF support the Flysky ibus receiver in the next version

**Comment by sukoshi1507** [comment]
It works as-is if you use PWM.

You mean using the flysky i-bus serial protocol ?

**Comment by sukoshi1507** [comment]
(And it should work using serial protocol since it's already supported : https://github.com/rs2k/raceflight/tree/raceflight/src/main/rx )

**Comment by opiswahn** [comment]
It works, I am using it myself. But you have to set it in CLI, as it us nut supported in the configuration yet.

**Comment by opiswahn** [comment]
set serialrx_provider=ibus

**Comment by pdwdw** [comment]
谢谢给位大神的指点，下午我去试试，希望以后能更加完善ibus，fs-i6这个控现在可是无敌了，fs-i6s月底也能到手，真是一代神控了

**Comment by pdwdw** [comment]
@opiswahn 下午按照说的在CLI里边对ibus经行了设置，接上接收机后在遥控设置界面里边没有任何反应，换了其它串口也是如此，对了我的飞空硬件是cc3d revo

PM said that in accordance with the inside of the CLI ibus been set, after the receiver connected to the remote setup interface inside no response, for the other serial too, for my fly empty hardware is cc3d revo

**Comment by pdwdw** [comment]
![4t xq 7x 6w w8e q3 vtw](https://cloud.githubusercontent.com/assets/18030200/14010735/eb3299f6-f1d2-11e5-8f7f-3966bfd846db.png)
![7odufn g gox_0_4s2_d _t](https://cloud.githubusercontent.com/assets/18030200/14010734/eb323b3c-f1d2-11e5-8e99-fac4017ba4ad.png)
![1jm7gm 9f3gk6g2 s y0bd](https://cloud.githubusercontent.com/assets/18030200/14010736/eb36cf44-f1d2-11e5-8e99-01786c042b88.png)
![104459mst6bsh2zsxcssss](https://cloud.githubusercontent.com/assets/18030200/14010733/eb2941a8-f1d2-11e5-88b3-d7f5050bf6df.jpg)
![104501tx0pfvp20r010imp](https://cloud.githubusercontent.com/assets/18030200/14010732/eb273570-f1d2-11e5-9263-68fa2b82ddd8.jpg)

**Comment by opiswahn** [comment]
I am not exactly sure what you mean, the translation is not that good :)
USART1 is on main-port, USART3 is on flexi-port

**Comment by pdwdw** [comment]
@opiswahn 所有的usart我都设置好了并一一试过了，但是在界面里遥控并没有任何反应，我保证接线没有错误
谢谢

**Comment by Jahnkeanater** [comment]
Whats the easiest way to hook up a serial rx? Is uart 6 in the oplink air port? The oplink port has 7 wires so gnd, vcc, rx, tx... What are the last 3 pins? It would be nice to use uart 6 and keep uart 1 and 3 open for osd and config.

**Comment by zipray** [comment]
@pdwdw 你测试过PWM模式吗？PWM各通道都是好的吗？

**Comment by proggod** [comment]
Please test betas and see if this issue is in any of them, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
