### ISSUE TITLE
Disable Motorstop when airmode is enabled.

### ISSUE THREAD

**Issue by Jahnkeanater** [rs2k/raceflight#139]
In cleanflight airmode disables motorstop to prevent the motors shutting off when doing low throttle maneuvers. We should bring that feature to raceflight also.

**Comment by blckmn** [comment]
Definitely. I'll look to bring that across this weekend.

**Comment by blckmn** [comment]
what pull request in CF has this? 
https://github.com/cleanflight/cleanflight/pull/1766 ?

**Comment by blckmn** [comment]
https://github.com/rs2k/raceflight/pull/141

**Comment by blckmn** [comment]
@Jahnkeanater have created the pull request here: https://github.com/rs2k/raceflight/pull/141 needs to be tested.

**Comment by blckmn** [comment]
@Jahnkeanater are you able to test?

**Comment by Jahnkeanater** [comment]
Yea once I get my new escs I would be happy to test it. I don't know how to build the binary's from source but I could try to figure it out. Or if you sent me a hex file for a revo. I don't really know my way around github yet.

**Comment by Jahnkeanater** [comment]
I'm guessing I would grab the source and swap out the 3 files you modified?

**Comment by blckmn** [comment]
Here is a build of Next for the Revo. There may be other issues with the version, but let me know if it works ok for you.

https://www.dropbox.com/sh/py6f5bwyyuvcv0q/AACqTlBet-nQIxbd0jmz0Jhqa

**Comment by Jahnkeanater** [comment]
Is this a special Airmode firmware or is this just RC11?

**Comment by Jahnkeanater** [comment]
Seems to work. I haven't flown it yet but the motors seem to behave the way they should.
