### ISSUE TITLE
Revolution does not run on battery power

### ISSUE THREAD

**Issue by Doosa34** [rs2k/raceflight#144]
When I plug in an external power source (battery), the FC does not boot (only the green light is on, there is no blinking).
When I connect my computer to the FC, it's okay, but if I connect meanwhile battery, then the connection is broken.

**Comment by blckmn** [comment]
Hi there. This will be very specific to your setup / FC and unlikely to be related to RF.

But we will try to help. Are you using a 5v BEC? How's it all connected?

**Comment by Doosa34** [comment]
I use 5V 3A PDB Bec, but I already tried with my ESC bec and the situation is the same. When I used the OpenPilot, it was not this issu, but I can imagine that I have a hardware something failure. :(

**Comment by blckmn** [comment]
I am pretty sure this is a hardware issue specific to the board in question. I will close now, however if it is firmware - please advise and we will look into it.

**Comment by Doosa34** [comment]
Problem solved! My GPS was connected in to the flexiport. After I disconnect the GPS and connect in to the main port, everything was good.
Thanks
