### ISSUE TITLE
F4 based FCs designed for Raceflight.

### ISSUE THREAD

**Issue by rs2k** [rs2k/raceflight#162]
I want to make sure I've got my information straight on all the FCs designed for RaceFlight.

@blckmn I have the BlueJay F4 listed on the first thread of the RCG RaceFlight Post.
@kc10kevin I have the KKNGF4 listed on the first thread of the RCG RaceFlight Post.
@MJ666 I'm missing a link for the AlienFlightF4.

I don't think I'll be posting links to the cloned Revos or Sparky2s. The QC of clones worries me. Bad FCs will give the firmware a bad reputation. The Sparky 2 clones have a lot of problems for example. The Falcon F4 and legitimate Sparky 2s aren't designed for RaceFlight, but they could have a link if their QC is up to par..

Anything else I need to add?

**Comment by blckmn** [comment]
looks good @rs2k. Perhaps the VRCORE?

**Comment by nathantsoi** [comment]
I'm designing a new one. Yet to be named... :)

**Comment by MJ666** [comment]
@rs2k for now the best link is www.alienflight.com. The AlienFlightF4 is not in production yet and we have not relesed as open source.

**Comment by kc10kevin** [comment]
Thanks for the link!
