### ISSUE TITLE
1wrie VCP no longer works in next.

### ISSUE THREAD

**Issue by rs2k** [rs2k/raceflight#169]
I believe changing the CPU clock is to blame. The feature worked well before merging.

**Comment by 4712** [comment]
I checked with SRF3, works fine. But 1wire-VCP is replaced with 4way-if...

**Comment by proggod** [comment]
1wire will be in new betas, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....

**Comment by 4712** [comment]
Sorry, no facebook, but I guess, I don't need to participate anyway...
