### ISSUE TITLE
Lux Board Flashing 

### ISSUE THREAD

**Issue by mattyra** [rs2k/raceflight#177]
Hello Guys,

Can we look at the flashing of the Lux Board please, i have yet to flash one successfully it comes up as successful but the light stays blue and the board won't boot...

Matty

**Comment by Clifftonlh** [comment]
I'm having the same problem with my Lux board..

**Comment by krisquigley** [comment]
I am having the same issues too

**Comment by slowGTO** [comment]
Same issue here as well on the Lux board.

**Comment by TheDuke99** [comment]
Yep same issue here, flashes fine in Cleanflight but Raceflight flashes and then nothing, Windows10 says the USB device had an issue and was not connected...

**Comment by mattyra** [comment]
@rs2k is the lux to be supported ??

**Comment by proggod** [comment]
@mattyra yes it will be, we are having some issues with our new boot loader on it, but we will get them figured out..

**Comment by mattyra** [comment]
Okay cool... Let me know if you need a test i have a few spare lux boards :-) @rs2k

**Comment by proggod** [comment]
Lux will soon be supported, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....

**Comment by timdonovanuk** [comment]
Joined the Facebook group, don't see any posts about betas, asked about LUX FC, didn't get a response. Wouldn't it be better to use github for what is good at rather than using Facebook for code releases and issue tracking?
