### ISSUE TITLE
Speed up CLI.

### ISSUE THREAD

**Issue by rs2k** [rs2k/raceflight#191]
TODO: Speed up CLI code.

**Comment by ankjaers** [comment]
Very welcome feature. Would be nice if the board didnt need to restart when leaving CLI and no changes were made.

**Comment by Jahnkeanater** [comment]
I have noticed when I run the dump command I need to do it several times to get everything. Its like the board is dumping faster than the cli can read.

**Comment by proggod** [comment]
The configurator in its current form has some issues, the beta branch we are working on has resolved alot of these, but its best you just paste in chunks when using the cli.   Its more the configurator and the way it works causing the issues.

**Comment by MJ666** [comment]
I think this problem was already fixed in the raceflight branch.
