### ISSUE TITLE
Revo board documentation incorrectly references the ports from the CC3D

### ISSUE THREAD

**Issue by TPhillip** [rs2k/raceflight#202]
[This page](https://github.com/rs2k/raceflight/blob/master/docs/Board%20-%20Revo.md) describes an 8-pin I/O connector that is identical to the CC3D, which is incorrect since the I/O port on the Revo is actually 10 pins. This can be confusing since the pin-outs do not match up and there is no documented way to determine how to wire the port properly.

**Comment by Jahnkeanater** [comment]
I agree I believe this information is wrong. It may be information for the CC3D not the REVO?

**Comment by proggod** [comment]
Check raceflightinfo.com and see if it looks correct there
