### ISSUE TITLE
OPLink

### ISSUE THREAD

**Issue by Tomcatt** [rs2k/raceflight#204]
Will there be any support for the OPLink? I'm thinking of ordering this little module.

**Comment by proggod** [comment]
Not yet, but we do have some plans for it in the future.

**Comment by Tomcatt** [comment]
Okay, please keep us posted.

**Comment by proggod** [comment]
If your not on the facebook group, you should join anything we do will be posted there.. :)

And rcgroups as well

**Comment by MAVProxyUser** [comment]
Is there a place to discuss future OPLink support? Who has the "plans" that are on deck now?
