### ISSUE TITLE
Do you have a plan to support all of the revonano function?

### ISSUE THREAD

**Issue by xfce** [rs2k/raceflight#21]
It seems the baro and mag doesn't support,  also because mag not support, i think the gps  not function ? 
and Do you have the plan? thanks

**Comment by rs2k** [comment]
The baro support just needs to be compiled in. The mag support is a work in progress.

https://github.com/rs2k/raceflight/pull/15

**Comment by xfce** [comment]
OK, thanks.
waiting for these function.
