### ISSUE TITLE
i2c driver file update for F4

### ISSUE THREAD

**Issue by blckmn** [rs2k/raceflight#35]
Would you like this updated to operate similar to the F3? using defines in the target file for setting up the function?

**Comment by rs2k** [comment]
Yes, that's going to be needed. I suspect part of the issues I'm getting with the GPIOs right now have to do with how other drivers like the I2C driver handle the pin setup.

**Comment by blckmn** [comment]
Done. I'll take a look tonight - and submit a pull request.
