### ISSUE TITLE
Ex.Bus (Jeti) support för Raceflight? 

### ISSUE THREAD

**Issue by kajakmannen** [rs2k/raceflight#4]
Ex.Bus (Jeti) support för Raceflight? 
Any code wizard that can make it happen? :D pretty please with suger on top.

Here is the documentation for Ex.bus protocol which maybe makes it easier to determine if it is possible or not.

http://www.jetimodel.com/en/show-file/642/

Thanks in advance for someone to reply on this issue, Kajaken

**Comment by rs2k** [comment]
It shouldn't be too difficult to implement, but I don't have time to do it myself right now. There are other things that need to happen first.

**Comment by blckmn** [comment]
I'll take a look on ebay see if i can't get a cheap second hand one of these to give this a go.

**Comment by blckmn** [comment]
Crikey. Those Jeti units are expensive! I don't think I'll be getting one anytime soon. :P

**Comment by hydra** [comment]
@kajakmannen Best to request for cleanflight support, then @rs2k can merge it after it's done and tested by the cleanflight team including @ProDrone who looks after the failsafe support.

**Comment by hydra** [comment]
Ahh, I see you already requested it here: https://github.com/cleanflight/cleanflight/issues/1513

You can probably close this issue.

**Comment by blckmn** [comment]
https://github.com/cleanflight/cleanflight/pull/1709 has been brought into raceflight here https://github.com/rs2k/raceflight/pull/143

If it can be tested @kajakmannen it can be merged.

@marv-t if you are happy also.

**Comment by kajakmannen** [comment]
So did I understand you right that ex.bus is implemented in raceflight now or??  Not so used to the routines here on got hub :) I would love to test it. Exbus should make it possible for telemetry also right?

**Comment by marv-t** [comment]
At the moment the following telemetry data are transmitted:
voltage, current, capacity and altitude.

On GPS I'm still working (waiting for GPS module).

Small changes are still in the pipeline, but basically no effect on the current functions.

@kajakmannen 
Please connect rx and tx from the fc with a 2k7 resistor. Connect the receiver on the rx pin.
-> have fun

**Comment by proggod** [comment]
Please test betas and see if this issue is in any of them, closing this issue since its based on an old version of our binaries, if you want access to betas please join our group at https://www.facebook.com/groups/1023175947742218/

Just trying to get github cleaned up so people can report issues with our betas....
