### ISSUE TITLE
Won't ARM: averageWaitingTasks100 too high - scheduler

### ISSUE THREAD

**Issue by blckmn** [rs2k/raceflight#42]
if (isCalibrating() || (averageWaitingTasks100 > 100)) {
            warningLedFlash();
            DISABLE_ARMING_FLAG(OK_TO_ARM);
        } else {
            if (ARMING_FLAG(OK_TO_ARM)) {
                warningLedDisable();
            } else {
                warningLedFlash();
            }
        }

**Comment by blckmn** [comment]
Consistently sitting at about 400+ starts at above 700... but comes down and stalls at 410-420

**Comment by rs2k** [comment]
I'll take a look at this when I get back in town.

**Comment by blckmn** [comment]
given the calculation for the averageWaitingTasks100 includes a multiple of 100 ... then the condition > 100 will imply only 1 waiting task. Perhaps it is meant to be > 1000? to allow for up to 10 tasks to be running in the background? I have mine set at 500 and it arms without issue.

**Comment by rs2k** [comment]
I'll set it to 1000 and see what happens

**Comment by rs2k** [comment]
Seems to be okay at 1000.

**Comment by rs2k** [comment]
No problems and excellent flight results at 1000 on both 4KHz and 8KHz motor output.

**Comment by blckmn** [comment]
Works great for me too :) thanks @rs2k
