### ISSUE TITLE
OneShot125: Updating motors after every control loop

### ISSUE THREAD

**Issue by blckmn** [rs2k/raceflight#43]
With control loop at 250us, there is not enough delay (<20us in most cases) before next motor signal at full throttle.

This means some (possibly a lot of) ESCs won't calibrate. Confirmed on scope, and confirmed problem with Dys BLheli and Lumenier Simonk Autoshot ESCs. @MJ666 advises similar symptoms on AlienFlightF4 prototype/kiss ESCs.

ESCs work fine (albeit sluggish) with OneShot disabled.

**Comment by rs2k** [comment]
I haven't had any problems calibrating oneshot at 4KHz. I'm only calibrating to a max throttle of 1850 to avoid this problems. Multishot will eventually solve this problem.

**Comment by blckmn** [comment]
I'll play with fastPWM and see if it works instead.

**Comment by MJ666** [comment]
Not an option here yet since we use 12A an 18A Kiss ESC's. We will give calibrating with 1850 an try soon.

**Comment by blckmn** [comment]
Just added some code to test ... essentially allowing the use of motor_pwm_rate for OneShot125.

Setting it to 800 (using CLI) and the Lumenier ESCs calibrate ok. I can then set it to 2000 and the ESCs still run fine (but with an update every 500us) :)

**Comment by MJ666** [comment]
We just tested this fix with the kiss ESC's. This working well. Thanks.

**Comment by blckmn** [comment]
Awesome! :) I'll close this one then.
