### ISSUE TITLE
Quanton FC

### ISSUE THREAD

**Issue by ther0x** [rs2k/raceflight#74]
Hi everyone

Is this release compatible with quanton FC?
I'm tring to find out an alternative to Taulabs

Thanks :)

**Comment by blckmn** [comment]
We could most likely create a target for it. Are these units still available? Would you be willing to test - I don't have any details on the board (pins outs devices etc).

**Comment by ther0x** [comment]
Thanks!
I have those informations

Quanton Pinout/Wiring

https://docs.google.com/spreadsheets/d/1DNAjixNGpjG3VyTk61cjjHc94rMEi0_3QG-DWvZ9cbU/edit#gid=0

And I have asked for F4 support into another fork of cleanflight

https://github.com/sambas/cleanflight 
I have to make make TARGET=COLIBRI but i'm not able

**Comment by blckmn** [comment]
I'll look to adding a target in the next 1-2 days. It will need to be tested by you as I don't have the board.

**Comment by ther0x** [comment]
Beautiful! Thanks :)

**Comment by blckmn** [comment]
I've added a target in the latest pull request.

**Comment by ther0x** [comment]
Yeah thanks! I'll try and let you know :)

**Comment by ther0x** [comment]
Hi, any news about it?

**Comment by blckmn** [comment]
Hi therox. You can pull the latest code and build the Quanton target. It's not tested as I don't have a unit. If you can test and provide feed back we can make any necessary adjustments. Ta.

**Comment by ther0x** [comment]
Sorry blckmn...is there an help or tutorial to make it? sorry, I'm a noob... :/

**Comment by IdefixRC** [comment]
Here you go:
HEX: https://drive.google.com/file/d/0B8lA7b3y0usFSElWTmo1R0NNaUk/view?usp=sharing
BIN: https://drive.google.com/file/d/0B8lA7b3y0usFVkw4RzRQRnBwYUk/view?usp=sharing

**Comment by ther0x** [comment]
Let me try, very busy...sorry :/
