### ISSUE TITLE
Merge iBUS from BetaFlight

### ISSUE THREAD

**Issue by opiswahn** [rs2k/raceflight#80]
Would be nice to have iBUS Support, since PWM kinda sucks. Boris has already done it in BetaFlight, so the merge should be not that big of an issue.

**Comment by blckmn** [comment]
I'll take a look tonight.

**Comment by blckmn** [comment]
This is already done :)

**Comment by opiswahn** [comment]
oh, cool, then i'll be waitng for the next release :)

**Comment by opiswahn** [comment]
Well, it can be enabled in cli, but doesn't work otherwise. Same setup works with cleanflight and naze. It is a bit hard to compare or merge the code, since realflight doesn't seem to be a beta- or cleanflight branch, whyever...
