### ISSUE TITLE
Add OPBL target for Quanton/Colibri

### ISSUE THREAD

**Issue by tracernz** [rs2k/raceflight#99]
Neither target has bootloader pads or buttons so it is very inconvenient to flash them/requires SWD the first time. TBS Colibri is a legitimate clone of the Quanton with some features removed and shrunken down, so should be able to support both boards with the Quanton target.

Both come stock with TauLabs bootloader which is essentially the same as OPBL so should be trivial to add. Memory organization (same for both): https://github.com/d-ronin/dRonin/blob/next/flight/targets/quanton/fw/memory.ld

**Comment by blckmn** [comment]
@tracernz do you want to do this one? - do you have a unit?

**Comment by tracernz** [comment]
I could probably do this, shouldn't be much work.
